# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) Microsoft Corporation. All rights reserved.
#
# Makefile for building the IPE module as part of the kernel tree.
#

obj-$(CONFIG_SECURITY_IPE) += \
	eval.o \
	hooks.o \
	fs.o \
	ipe.o \
	policy.o \
	policy_fs.o \
	policy_parser.o \
	audit.o \
