#
# Integrity Policy Enforcement Test Suite
# Copyright (C), Microsoft Corporation, All Rights Reserved.
#
import ipe.util as util

def basic(path):
    """
        basic:
          very basic smoke test to ensure IPE is working
          on self-contained, native binaries.

        Invokes a helper binary located in a subfolder of
        @path. Returns the return code of the execution.

        @path: path to the root of the test resource folder
        @rv: (return code, stdout, stderr)
    """
    return util._exec(f"{path}/bin/hello", [])

def interpreter(path):
    """
        interpreter:
          very basic smoke test to ensure IPE is working
          on scripts invoked by execve. (Utilizing shebangs)

        Invokes a script located in a subfolder of
        @path. Returns the return code of the execution.

        @path: path to the root of the test resource folder
        @rv: (return code, stdout, stderr)
    """
    return util._exec(f"{path}/script/hello.sh", [])

def exec_memfd(path):
    """
        exec_memfd:
          very basic smoke test to ensure IPE is working
          on memory-based file-discriptors, with verified content.

        As of IPE's initial release, this should always be blocked,
        for all available properties.

        Invokes a helper binary located in a subfolder of
        the path passed in. Returns the return code of the execution

        @path: path to the root of the test resource folder
        @rv: (return code, stdout, stderr)
    """
    return util._exec(f"{path}/bin/memfd_test", [f"{path}/bin/hello"])

def ffi(path, securityfs_root):
    """
        ffi:
          Basic test of foreign-function invocation via code trampolines
          (such as those generated by libffi).

        This invokes libffi (which is used in python) via python's ctypes
        module.

        @path: path to the root of the test resource folder
        @rv: None
    """
    #To load libffi into python address space
    util.ipe_enforce_mode_off(securityfs_root)
    import ctypes
    util.ipe_enforce_mode_on(securityfs_root)
    ctypes.CFUNCTYPE(None, ctypes.c_int)(lambda x: None)
